name: Continuous Integration

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
        
    steps:
      - uses: actions/checkout@v4  # Updated to latest version (v4)
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4  # Updated to latest version (v4)
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'  # Enable caching for faster installs
          
      - name: Install dependencies
        run: npm ci
          
      - name: Build project
        run: npm run build  # Remove --if-present if you're sure the script exists
        
      # Uncomment if you have tests
      - name: Run tests
        run: npm test
